# Permalinks
permalink:        pretty

# Setup
title:           Apoorva Pandey
tagline:          "Welcome to my life"
description:      'Developer at Software Incubator | Open Source Contributor'
url:              http://www.apoorvaeternity.github.io
baseurl:

author:
  name:           'Apoorva Pandey'
  url:            https://www.apoorvaeternity.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/apoorvaeternity/apoorvaeternity.github.io


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: apoorvapandey365@gmail.com
  facebook: apoorvaeternity
  flickr:
  github: apoorvaeternity
  instagram: eternityapoorva
  linkedin: apoorva-pandey-bb6603130
  pinterest:
  rss: # Set to anything to generate RSS icon. Don't want it though since it just adds unnecessary clutter.
  twitter: eternityapoorva
  stackoverflow: 

# Your disqus shortname, entering this will enable commenting on posts
disqus: apoorvaeternity-github-io

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-120867506-1


# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Use the following plug-ins
plugins:
  - jemoji # Emoji please!
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE.md
    - README.md
